# Generated by Django 2.1.4 on 2019-03-20 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Month',
            },
        ),
        migrations.CreateModel(
            name='MotivationSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_series', models.CharField(max_length=200)),
                ('motivation_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('series_summary', models.CharField(max_length=200)),
                ('motivation_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.MotivationCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Day',
            },
        ),
        migrations.AddField(
            model_name='motivation',
            name='motivation_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='motivation_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='motivation',
            name='motivation_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.MotivationSeries', verbose_name='Day'),
        ),
    ]
