# Generated by Django 2.1.4 on 2019-03-20 21:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190320_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_day', models.CharField(max_length=200)),
                ('motivation_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('day_summary', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Day',
            },
        ),
        migrations.CreateModel(
            name='MotivationMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_month', models.CharField(max_length=200)),
                ('month_summary', models.CharField(max_length=200)),
                ('month_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Month',
            },
        ),
        migrations.RemoveField(
            model_name='motivationseries',
            name='motivation_category',
        ),
        migrations.RemoveField(
            model_name='motivation',
            name='motivation_series',
        ),
        migrations.DeleteModel(
            name='MotivationCategory',
        ),
        migrations.DeleteModel(
            name='MotivationSeries',
        ),
        migrations.AddField(
            model_name='motivationday',
            name='motivation_month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.MotivationMonth', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='motivation',
            name='motivation_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.MotivationDay', verbose_name='Day'),
        ),
    ]
