# Generated by Django 2.1.4 on 2019-03-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190320_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationday',
            name='day_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
